kumuluzee:
  name: rso-airline-booking
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
  - jndi-name: jdbc/fri_airline
    connection-url: ${KUMULUZEE_DATASOURCES0_CONNECTIONURL}
    username: postgres
    password: pass
    max-pool-size: 20

app-properties:
  external-services:
    enabled: true
  healthy: true